### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by CDRX2** [thomasloven/lovelace-layout-card#101]
The map card seems to run into some issues loading when inside a layout card. I've narrowed it down to its being included in a layout card (same config with stack-in-card shows the map).

HA 108.2
Supervisor 2020.11.1
HassOS 4.17

Error in the browser dev tools:

` Uncaught (in promise) Error: Map container is already initialized.
    at i._initContainer (​)
    at initialize (​)
    at new i (​)
    at Object.ne [as map] (​)
    at r (​)
    at async HTMLElement.value (​)`

At your disposal should you need any more information.

**Comment by CDRX2** [comment]
Must have been something else in my HA, just rebooted and now it works. Always reboot before asking for help!!!

**Comment by thomasloven** [comment]
Please try version 2.0.0.

**Comment by CDRX2** [comment]
Sorry for the delay, I've just upgrade to 2.2.0 and it seems this has been solved.
