### ISSUE TITLE
Unable to use EDIT functionality of individual cards

### ISSUE THREAD

**Issue by aw-jansen** [thomasloven/lovelace-layout-card#104]
Hi, It seems that using the card-layouts disables the option for individual cards to be edited (since all cards are seen as one single card). This makes editing complex dashboards a rather cumbersome operation since only the raw configuration editor cen be used. Would be great to have an option to still be able to edit cards through the ui.

**Comment by thomasloven** [comment]
This can now be done with version 2.0.0 by using a view layout instead of a layout-card.
