### ISSUE TITLE
Provide a padding on top when in panel mode

### ISSUE THREAD

**Issue by DeepCoreSystem** [thomasloven/lovelace-layout-card#108]
I have a view where I want to use the layout-card. The view is in panel mode and the contained cards are snug to the upper bar.
![grafik](https://user-images.githubusercontent.com/3703938/111027675-07bbbb00-83f2-11eb-8b2c-0e912fb15842.png)

The 'problem' lies here: 
https://github.com/thomasloven/lovelace-layout-card/blob/90bcb7f1561056b4a7584ee6b33a3ca7a4f08181/layout-card.js#L40-L45

If I remove line 44, I get the result I want:
![grafik](https://user-images.githubusercontent.com/3703938/111027693-2b7f0100-83f2-11eb-856a-a79022db7ba7.png)

**Comment by thomasloven** [comment]
This should be fixed with 2.0.0.
Please confirm.

**Comment by EliotHertenstein** [comment]
> 
> 
> I have a view where I want to use the layout-card. The view is in panel mode and the contained cards are snug to the upper bar.
> ![grafik](https://user-images.githubusercontent.com/3703938/111027675-07bbbb00-83f2-11eb-8b2c-0e912fb15842.png)
> 
> The 'problem' lies here:
> 
> https://github.com/thomasloven/lovelace-layout-card/blob/90bcb7f1561056b4a7584ee6b33a3ca7a4f08181/layout-card.js#L40-L45
> 
> If I remove line 44, I get the result I want:
> ![grafik](https://user-images.githubusercontent.com/3703938/111027693-2b7f0100-83f2-11eb-856a-a79022db7ba7.png)

I'm trying to figure out how to get this kind of spacing. What did you do to add the spacing in the first place?
