### ISSUE TITLE
no more column_width: [xxx,xxx]

### ISSUE THREAD

**Issue by maddeuce** [thomasloven/lovelace-layout-card#111]
Just notice all my card with custom column width within the card is all gone.  All my column width turn into evenly divided to the total column width now.  Is the old customable column width feature gone in the new version??

**Comment by thomasloven** [comment]
Some functions have indeed been removed, that's what 
> Also lots of breaking changes
>
>Read the readme BEFORE you upgrade.

was meant to mean.

Please check out the improved Grid Layout for more fine grained control.

**Comment by Aura-Mancer** [comment]
I understand, though, a guide on how to acomplish the same thing the "column_width" option did in CSS would be really appreciated. All my layout-cards "broke" and I don't understand how to use CSS to acomplsih the same thing.

**Comment by Aura-Mancer** [comment]
Nevermind, things weren't working because I didn't erase my browser cache 😅
