### ISSUE TITLE
Changing layout type hides badges

### ISSUE THREAD

**Issue by Skeletorjus** [thomasloven/lovelace-layout-card#115]
I have a row of badges at the top of my view. If I change layout type to anything but default, the badges disappears. Changing the layout back to default makes the badges come back again.

Great work getting this available in the UI editor, by the way!

**Comment by thomasloven** [comment]
I actually chose not to support badges because they are so seldom used.
Try this: https://github.com/thomasloven/lovelace-badge-card

And thank you!
