### ISSUE TITLE
Layout: option causes conflicts with other custom cards.

### ISSUE THREAD

**Issue by Aura-Mancer** [thomasloven/lovelace-layout-card#118]
I want to define a gird_area, inside of the layout option, but the card I'm doing that in has an option that it's also called layout. So, I can use the options of layout-card, or the one of the custom card I'm using. Is there a way to fix this?

**Comment by scooper1** [comment]
the layout keyword wipes out the button card 
can you change the option name or have a second option name that is less likely to be used via other cards please

**Comment by thomasloven** [comment]
The layout key is reserved for this use from Home Assistants side. But me, RomRider and the frontend team are in discussions about how to solve this.

Thanks for raising this.

**Comment by scooper1** [comment]
Appreciate that problem is overall issue with layout key but was not causing problems untill use in version 2.0 please fix issue in this card and don't try to force every else to change because you made a decision to use that key without expecting problems.  In reality I personally think it would been better to end support for old layout card and start a new layout card with new name  it would have not broken a lot of systems doing it that way

**Comment by thomasloven** [comment]
As I said, this is how Home Assistant has specified this parameter SHOULD be used.
But as I also said, we are discussing how to solve this, and it will be changed.

Please let me know where I forced you to click the upgrade button, and I will immediately remove that.

**Comment by thomasloven** [comment]
The card option `layout` has been renamed `view_layout` after discussions with RomRider and Zack who is developing the drag-and-drop layout.

Apologies for the inconvenience.

**Comment by scooper1** [comment]
No you did not force me but as you said the card had got to complex to maintain  working with likely system updates.  as to force me no but a Very annoying hacs warning to update card is enough  I glad that you have changed the name  if you had spotted this in the first place I would have been happy to modify my  settings but layout problem was not fixable and you did not give me conference that it would be changed.   It was my option to upgrade but maybe would have been a nice idea to put this out as beta to find issues.   I do appreciate this is good will type of coding I do like what you have done but it was  hard to understand your thinking as there could have. Been some more full examples   I am trying to be positive and not anoy you On 18 Mar 2021 21:40, Thomas Lovén ***@***.***> wrote:
As I said, this is how Home Assistant has specified this parameter SHOULD be used.
But as I also said, we are discussing how to solve this, and it will be changed.
Please let me know where I forced you to click the upgrade button, and I will immediately remove that.
