### ISSUE TITLE
No settings for Layout in Summary View Configuration

### ISSUE THREAD

**Issue by WarmCatUK** [thomasloven/lovelace-layout-card#119]
<img width="597" alt="Screenshot 2021-03-16 at 11 58 20" src="https://user-images.githubusercontent.com/32871908/111306044-9f6a1500-864f-11eb-88be-4d8519f623fe.png">

There are no options. Cache has been flushed etc.
HA Core: core-2021.2.3
Hassio: Home Assistant OS 5.12

**Comment by thomasloven** [comment]
Yes. My bad for not setting 21.3 as a requirement.
Upgrade and it will be fine.

**Comment by WarmCatUK** [comment]
Excellent, it’s as you say. Updated and now I can add configuration via the layout tab :-)
