### ISSUE TITLE
Allow width override for mobile

### ISSUE THREAD

**Issue by bacco007** [thomasloven/lovelace-layout-card#12]
It would be good if the width attribute can be overridden for mobile devices

**Comment by thomasloven** [comment]
With the latest changes it's possible to create a responsive design by nesting layout-cards and playing around with the options

![responsive 1](https://user-images.githubusercontent.com/1299821/54021845-54c87f00-4191-11e9-96e9-d070b9291f42.jpg)
![responsive 2](https://user-images.githubusercontent.com/1299821/54021849-57c36f80-4191-11e9-90bb-683c38578858.jpg)
![responsive 3](https://user-images.githubusercontent.com/1299821/54021853-5a25c980-4191-11e9-97ed-e80fffc6c96a.jpg)
