### ISSUE TITLE
column widths 

### ISSUE THREAD

**Issue by scooper1** [thomasloven/lovelace-layout-card#129]
it would be nice to be able set different column widths in a vertical layout

**Comment by thomasloven** [comment]
If you think about it, that's really only useful for horizontal layout, because otherwise you can't repeatably predict which card ends up in which column anyway.

And when you get there, you realize that's really what the Grid layout does...

**Comment by scooper1** [comment]
Vertical ?  With break cards ?  No problems with span and. With column it's mobile friendly On 22 Mar 2021 14:18, Thomas Lovén ***@***.***> wrote:
If you think about it, that's really only useful for horizontal layout, because otherwise you can't repeatably predict which card ends up in which column anyway.
And when you get there, you realize that's really what the Grid layout does...

**Comment by thomasloven** [comment]
Good point about the break cards.

I'll give it another round of thought.

**Comment by thomasloven** [comment]
Know what?

I was about to tell you how the Grid layout will do almost exactly what you want by using functions built into your browser, and is much better than if I were to try to emulate the same functionality for the column based layouts.

Then I realized I don't have to emulate it. I'll just use it.
So now ALL layouts are Grid Layouts behind the scenes!

The end user won't notice, and I won't have to worry.

Check out the new `column_widths` option in 2.2.3.

**Comment by scooper1** [comment]
sounds like a win win - hopefully it will not upset the android home assistant app
the last change for some reason upset my cast lovelace layout to google hub - it spaced it around 300px to the right - more than likely it was my error but only way i could fix it was to vertical-stack card instead of the layout card 
your layout card is used on a lot of my screens

**Comment by thomasloven** [comment]
Should be fine on android 5 or later https://caniuse.com/?search=grid

I'll take a look at cast.
