### ISSUE TITLE
[Feature Request] Column_Width should be a per column value

### ISSUE THREAD

**Issue by Shadowpheonix** [thomasloven/lovelace-layout-card#13]
Please make Column_Width a per column value.  Being able to define minimum & maximum widths for each column would be extremely beneficial, as some cards look horrible if they get too small, while others look bad when they get too large.

On a side note, I believe that your entire collection of custom cards are pretty much vital to making LoveLace even remotely usable.   Thank you VERY much for all the work that you do.

**Comment by WagnerBeccard** [comment]
Not too shure.. But isnt this https://github.com/thomasloven/lovelace-layout-card#max-width what you're asking for?

**Comment by Shadowpheonix** [comment]
> Not too shure.. But isnt this https://github.com/thomasloven/lovelace-layout-card#max-width what you're asking for?

I am actually asking for a minimum width to go with that maximum to allow for more precise control.  (IE: I want to be able to specify things like Min = 400px & Max = 500px, Min = 25% & Max = 250px, Min = 500px & Max = 75%, Min = 300px & Max = 300px, etcetera).

**Comment by thomasloven** [comment]
That's bound to cause unresolvable conflicts.

Min: 25%, max 250 px. What about if your screen is more than 1000 pixels wide?

`column_width` is used to calculate how many columns there will be depending on the screen width.  
`max_width` is used to set their sizes.
