### ISSUE TITLE
please bump the version number to 2.2.3....

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-layout-card#131]
My Home Assistant version: 2021.XX.X

Layout-card version (FROM BROWSER CONSOLE):
should be 2.2.3 but still lists:
```
var Ot="2.2.2"
```

What I am doing:
judast updated t0 2.2.3
What I expected to happen:
have it display that in the console
What happened instead:
shows 2.2.2

<img width="598" alt="Schermafbeelding 2021-03-22 om 23 02 39" src="https://user-images.githubusercontent.com/33354141/112064115-c13d2d80-8b62-11eb-8719-1da707eb7e49.png">

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Yeah... I made a mistake there. I think if you reinstall it it will show up as 2.2.3, and actually contain the other changes between 2.2.2 and 2.2.3 too...

**Comment by Mariusthvdb** [comment]
<img width="273" alt="Schermafbeelding 2021-03-23 om 14 53 06" src="https://user-images.githubusercontent.com/33354141/112157455-83ceb380-8be7-11eb-9d15-ddd80bf2be42.png">

thanks!
