### ISSUE TITLE
Options from graphical card editor not properly stored in the final YAML

### ISSUE THREAD

**Issue by xbaro** [thomasloven/lovelace-layout-card#134]
My Home Assistant version: 2021.3.4

Layout-card version (FROM BROWSER CONSOLE): 2.2.3

The Layout Options box content is stored in a YAML field called "layout_options", and has no effect. When edited on the YAML editor and copied those options under the "layout" field, the options work fine.

**Comment by thomasloven** [comment]
Make sure to completely clear your browser cache. See instructions near the bottom of the install guide linked from the readme.

**Comment by Jpsy** [comment]
I don't think this is a caching issue.
I witness the same problem in Chrome and Safari and clearing the cache does not solve it.

What may be missing in the OP's report is that this is not happening for view layouts (which work fine), but for layout-cards. 

Data entered into the field **Layout options** is stored in yaml under the key `layout_options`. 
But the editor also creates a reference in the key `view_layout` that points to `layout` (which is empty).
The empty `view_layout` seems to overwrite the `layout_options` setting and the card does not work as expected.

**Example:**

![image](https://user-images.githubusercontent.com/1806058/113755246-63871480-9710-11eb-9b11-7c77595f4798.png)

Generated YAML code:

      type: 'custom:layout-card'
      layout_type: grid
      layout: &ref_0 {}
      cards: []
      layout_options:
        grid-template-columns: 1fr 1fr
      view_layout: *ref_0

Correct YAML code:

      type: 'custom:layout-card'
      layout_type: grid
      cards: []
      layout_options:
        grid-template-columns: 1fr 1fr

**Comment by Jpsy** [comment]
I just discovered that the following YAML code works too:

      type: 'custom:layout-card'
      layout_type: grid
      layout: &ref_0
        grid-template-columns: 1fr 1fr
      cards: []
      view_layout: *ref_0

This code can be even simplified (while still working):

      type: 'custom:layout-card'
      layout_type: grid
      layout:
        grid-template-columns: 1fr 1fr
      cards: []

So to get it all working you have to use either `layout_options` OR `layout`, but not both (as generated for a fresh Layout Card).

I have a feeling, that the additional view_layout reference in the first version is generated for a reason.
`view_layout` as well as `layout`/`layout_options` both accepts `grid-*` CSS styles and `place-self`. Is this overlapping functionality the deeper reason for referencing the `layout` field into the `view_layout` field?

If I get this right, `view_layout` is basically meant to style the card in reference to an outer View Layout, while `layout`/`layout_options` is meant to style the grid for the card itself and its children. But honestly, this is quite confusing when reading the docs. If you reference / mirror the content anyway, wouldn't it make sense to use just one single field to take all `grid-*` styles for all cards? No matter whether they are children of a grid, hosting a grid or both?

**Comment by Jpsy** [comment]
And one more finding:

The combination of `layout` and `view_layout` is the only version that currently works AND survives editings.
All other combinations either don't work or are destroyed/modified during the next editing.
So this is currently the only stable solution:

    type: 'custom:layout-card'
    layout_type: grid
    layout: &ref_0
      grid-template-columns: 1fr 1fr
    cards: []
    view_layout: *ref_0

To get there from a freshly generated Layout-Card you only have to replace the `layout_options` key by `layout`.

**Comment by omayhemo** [comment]
This actually partly worked for me, with the exception that the individual card's grid-view is still not respected, as per my Bug report.

**Comment by omayhemo** [comment]
Woops, nope these settings keep getting wiped out when I save.  It's inconsistent.  Sometimes they do sometimes they don't.

**Comment by Jpsy** [comment]
Strange. Seems stable for me if I follow the last code example.
