### ISSUE TITLE
Break not found

### ISSUE THREAD

**Issue by Abuelika** [thomasloven/lovelace-layout-card#135]
My Home Assistant version:  2021.3.4

Layout-card version (FROM BROWSER CONSOLE): 2.2.3

the break option has stopped working ... Is it normal?

![alt text](https://i.ibb.co/xsWpb7G/break-layout.jpg)

**Comment by ViggoGaming** [comment]
Hey @Abuelika 
I get the exact same problem on the same version of Home Assistant.
I hope this will be fixed as soon as possible.

- Victor

**Comment by thomasloven** [comment]
How did you install layout-card?

**Comment by ViggoGaming** [comment]
Hey @thomasloven 
I installed it trough HACS community store.
![image](https://user-images.githubusercontent.com/26089698/113614904-738cee80-9653-11eb-8c3c-f8b425a6d8c0.png)

**Comment by Abuelika** [comment]
Hi @thomasloven 

After installing the last stable version of homeassistant this error appeared, before it was working correctly.
I have also updated layout-card from HACS

I have created a new configuration, and it does not accept -break

**Comment by thomasloven** [comment]
The last 7 releases of layout-card are named - in order:
- 2.0.0: **BREAKING!** Layout-card 2.0
- 2.1.0: **2.0 is BREAKING** - Make grid layouts fully responsive
- 2.1.1: **2.0 is BREAKING** - Improved grid layout responsiveness
- 2.2.0: **BREAKING!** layout is renamed view_layout
- 2.2.1: **2.2.0 IS BREAKING**
- 2.2.2: **IF YOU'RE UPDATING FROM EARLIER THAN 2.0 - YOUR. CONFIG. WILL. NOT. WORK. WITHOUT. CHANGES.**
- 2.2.3: **PLEASE READ THE RELEASE NOTES FOR THE LAST COUPLE OF RELEASES**



This is also helpfully displayed every time you click the update button in HACS:
![image](https://user-images.githubusercontent.com/1299821/113782032-d785e480-9731-11eb-96d7-ee7022c5fefc.png)
