### ISSUE TITLE
Badges are hidden if choose masonary view

### ISSUE THREAD

**Issue by kornelremete** [thomasloven/lovelace-layout-card#136]
My Home Assistant version: 2021.3.4

Layout-card version (FROM BROWSER CONSOLE): 2.2.3.

What I am doing: If I choose masonary or horisontal or vertical layout than I can't see the Badges

What I expected to happen: only the cards shoould be reorganised

What happened instead: cards are reorganised but it hides the badges

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by efekthalo** [comment]
Same issue. Badges are not visible

**Comment by n00bcodr** [comment]
Same issue, not just masonry view though, any view other than default view, badges disappear.

**Comment by arrikhan** [comment]
confirmed, all cards

**Comment by thomasloven** [comment]
This is expected. I chose not to include badges. You can reintroduce them with [badge-card](https://github.com/thomasloven/lovelace-badge-card).

**Comment by enuzzo** [comment]
Great Thomas! Thanks for your clarification.

Luca C.


On 30 June 2021 at 00:41:48, Thomas Lovén ***@***.***) wrote:

This is expected. I chose not to include badges. You can reintroduce them with badge-card.
