### ISSUE TITLE
New Documentation?

### ISSUE THREAD

**Issue by omayhemo** [thomasloven/lovelace-layout-card#139]
Your work is outstanding and I appreciate your contribution to the community.

I've been struggling a bit with the layout card. The instructions and what appears to be a new UI implementation that is not documented seem to be in conflict.  Grid settings are not really working as I expect and sometimes I find the settings I input get wiped out on save.

For example the documentation:
![image](https://user-images.githubusercontent.com/2934415/114404720-98112b00-9b6b-11eb-83ce-2652247a1731.png)

Versus what I actually see:
![image](https://user-images.githubusercontent.com/2934415/114404799-a8290a80-9b6b-11eb-919c-fc0545130ebc.png)
![image](https://user-images.githubusercontent.com/2934415/114404834-b1b27280-9b6b-11eb-82fd-cd5c39bc1d3d.png)

Right off the bat, the custom card type differs.  The structure of the YAML differs, especially with regard to the Layout options section.

Any insight on that disparity?

**Comment by thomasloven** [comment]
The cause of the disparity lies right above your screenshot in the cut-off text that says "Configuration for view:"

As in "Not configuration for card:".
Using a layout-card is a special case - not the documented base case - and adjustments will need to be made.
