### ISSUE TITLE
grid areas css style

### ISSUE THREAD

**Issue by madmicio** [thomasloven/lovelace-layout-card#149]
is there a possibility to take complete control of the css style for the grid layout? is there the possibility to take the css control of every single area ?. to set background, padding etc etc of each single area?

**Comment by mrpharderwijk** [comment]
+1

**Comment by thomasloven** [comment]
No. That's not what CSS grid does.

**Comment by mrpharderwijk** [comment]
> is there a possibility to take complete control of the css style for the grid layout? is there the possibility to take the css control of every single area ?. to set background, padding etc etc of each single area?

You can use mod-card to do what you need…
