### ISSUE TITLE
grid-layout variable row height?

### ISSUE THREAD

**Issue by urielz** [thomasloven/lovelace-layout-card#150]
Is it possible to have variable row height in grid-layout view?

Specifically I'm trying to avoid blank spaces as shown in figure:

![example](https://user-images.githubusercontent.com/11670888/121559799-4e1eb700-c9ed-11eb-8cfc-23cb7213f037.jpeg)

Thank you!

**Comment by thomasloven** [comment]
I can't reproduce the problem.
Please use the issue template to help you provide enough data.
