### ISSUE TITLE
grid display

### ISSUE THREAD

**Issue by bublikOff** [thomasloven/lovelace-layout-card#152]
As I understood CSS grid it show be displayed as GRID
So ... grid-layout is rendedred width "display: inline" instead of "display: grid".
Ive tried something like "grid-display: grid'
Any idea?  how to apply "display: grid" to grid-layout

**Comment by thomasloven** [comment]
It's not supposed to be.
The `<div id="root">` inside `<grid-layout>` which in turn contains the cards has `display: grid`.
