### ISSUE TITLE
No Layout Options text-box appearing.

### ISSUE THREAD

**Issue by d2inco** [thomasloven/lovelace-layout-card#157]
Just ran across the layout-card and installed it.

I am not seeing the input area for the configuration showing up; I have the dropdown, but no input area.  Image is below.

I have restarted HASS (actually rebooted the whole VM as long as I was doing it) and reloaded the browser, as well, but no input area.  Switching to different layouts (default, grid, etc) has no effect.

![image](https://user-images.githubusercontent.com/5826360/126414730-d74f30fa-74d2-4530-b73d-1f0120d5e304.png)

**Comment by thomasloven** [comment]
This should be fixed in 2.3.1. The options box is now on the "SETTINGS" tab instead.

**Comment by pvillanyi** [comment]
Yea, but no "Layout Options" box...

**Comment by pvillanyi** [comment]
![layout](https://user-images.githubusercontent.com/99245307/154054765-5290c344-e80a-47f2-a80a-ea1496d2c875.JPG)

**Comment by thomasloven** [comment]
Please follow the issue template. That will help you provide the information I need to find the issue.
