### ISSUE TITLE
Issues with inputfields

### ISSUE THREAD

**Issue by Svarstad** [thomasloven/lovelace-layout-card#16]
Hi, the cards behave as they should, awsome btw :) but input fields in cards on mobile (Android) seems to just deselect them self while tapping them. Has anyone gotten experiense with this?

**Comment by thomasloven** [comment]
Please provide a minimal working example.

**Comment by Svarstad** [comment]
`title: Kitchen
icon: mdi:food
panel: true
path: kitchen
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: shopping-list
        title: Shoppinglist
`

**Comment by Svarstad** [comment]
*update* 
have also now set up custom updater and updated all cards 
![Skjermbilde 2019-03-22 kl  20 17 28](https://user-images.githubusercontent.com/24622052/54847774-91db5800-4cdf-11e9-926a-cb2e517d627a.png)

still same issue

**Comment by thomasloven** [comment]
And the problem only appears when you are using *all* those plugins?
