### ISSUE TITLE
No Badges appear

### ISSUE THREAD

**Issue by phoniclynx** [thomasloven/lovelace-layout-card#165]
Whenever you use the Layout Card, no matter what form/style you use (Grid, Masonry etc) if you put in a Badge with the default Lovelace UI, it will not appear with the layout cards enabled. If you switch over to the normal Lovelace Masonry card they show up.

**Comment by Andoramb** [comment]
I agree. My badges disappeared too :)

**Comment by BroManDudeGuyPhD** [comment]
Same, cannot find any mention in docs about badges. Tried "badges: true" but no dice

**Comment by philosowaffle** [comment]
Same, lost all my badges. I still see them in the layout code view, but they do not show on the dashboard.

**Comment by ildar170975** [comment]
Same for me.
https://community.home-assistant.io/t/layout-card-take-control-of-where-your-cards-end-up/147805/475?u=ildar_gabdullin
I am not using badges, just asking to clarify.

Here it was written by other person that badges are going to be "phased out from HA":
https://community.home-assistant.io/t/input-boolean-icon-ignored-in-badge/159704/16?u=ildar_gabdullin

**Comment by BroManDudeGuyPhD** [comment]
Phasing out badges? Why??

**Comment by Andoramb** [comment]
Well, if Petro says that, then it's good for me :)

**Comment by thomasloven** [comment]
Badges are phased out from automatically generated views, but they can still be added manually to the default views.
I chose not to include them in layout card because it would add too many options to place them in the right position. Check out [badge-card](https://github.com/thomasloven/lovelace-badge-card).
