### ISSUE TITLE
No option for "Masonry (layout-card)"

### ISSUE THREAD

**Issue by markrennie71** [thomasloven/lovelace-layout-card#167]
My Home Assistant version: 2021.11.1

Layout-card version : 2.3.1

What I am doing:
trying to use the card
What I expected to happen:
show "Masonry (layout-card)"
What happened instead:
doesn't show
**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

The option did show, then suddenly didn't, so I upgraded Ha and reinstalled this card. Same, no option. Then rebooted and then uninstalled and still the same.

**Comment by georgo** [comment]
Looks like you didn't attached javascript to your ui. Add following to your `configuration.yaml`:

```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
```

**Comment by thomasloven** [comment]
Please provide all related output from the browser console.
