### ISSUE TITLE
no layout option since 2.3.1

### ISSUE THREAD

**Issue by fullcavediver** [thomasloven/lovelace-layout-card#170]
My Home Assistant version:  I use ioBroker with Lovelace-UI 2.0.6

Layout-card version (FROM BROWSER CONSOLE): 2.3.1

Last working version: 2.3.0

In the last version 2.3.1, the LAYOUT tab is no longer visible and the cards can no longer be edited. Back to the version 2.3.0 fixes the bug.

![2021-11-28_121616](https://user-images.githubusercontent.com/49302111/143765628-fd38005f-320d-48d1-9038-18f821a452f6.png)
![2021-11-28_121841](https://user-images.githubusercontent.com/49302111/143765634-a9dd7a92-7cc8-4d27-8594-fe5db54646c4.png)

**Comment by thomasloven** [comment]
Layout options are moved to the Settings tab.
