### ISSUE TITLE
HACS inject wrong path to JS module

### ISSUE THREAD

**Issue by via-justa** [thomasloven/lovelace-layout-card#176]
My Home Assistant version: 2021.12.3

Layout-card version (FROM BROWSER CONSOLE): 2.3.1

What I am doing: Adding the card to the frontend

What I expected to happen: Resource will be added with the right settings
```
/local/community/lovelace-layout-card/layout-card.js?hacstag=156434866231
```
What happened instead: Resource is added with wrong path
```
/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866231
```
**Minimal** steps to reproduce:
Add the card via HACS

Error messages from the browser console:
The layout is not recognized. 
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Daniel15** [comment]
I'm getting a 404 even when I use that path, unfortunately. I do see the file when I look in `[path]/www/community/lovelace-layout-card/layout-card.js` so I'm not sure why I'm getting a 404 😕

**Comment by thomasloven** [comment]
This seems like an issue with HACS if anything.
