### ISSUE TITLE
Please help with grid having no gaps

### ISSUE THREAD

**Issue by tanker11** [thomasloven/lovelace-layout-card#177]
Hello,

I am a bit lost how to define a 3x3 grid view with no gaps in between.
I found a piece of code that could do, for example:

grid-template-columns: 100px 50px 100px;
grid-template-rows: 80px auto 90px;
column-gap: 0px;
row-gap: 0px;

But I am lost where to put this code.

What I have:
1.) Installed Layout-card via HACS
2.) Selected grid (layout-card) as a view type
3.) If I enter the above code into the Layout options edit field, nothing happens...

Thanks in advance for helping me out.

Robert

**Comment by thomasloven** [comment]
Layout options do not have semicolons
