### ISSUE TITLE
newest cardtools mismatching without layout card?

### ISSUE THREAD

**Issue by kloknibor** [thomasloven/lovelace-layout-card#18]
![image](https://user-images.githubusercontent.com/10560390/54877721-7f1d6c00-4e22-11e9-8f20-f69d13e16be6.png)

I have layout cards and card-tools both at the latest version but my GUI gets really slow and my chrome log gets full off errors. It seems to get stuck in some async loop... Anything I can do to fix this?

**Comment by thomasloven** [comment]
Is this still a problem?

**Comment by kloknibor** [comment]
I believe not, my sd card crashed so I started over and now it seems ok ;-)
