### ISSUE TITLE
HACS only display 2.3.1 as last Version for install

### ISSUE THREAD

**Issue by scheilch** [thomasloven/lovelace-layout-card#181]
My Home Assistant version: 
2021.12.10

Layout-card version (FROM BROWSER CONSOLE): 
not yet installed due to the Bug describing

What I am doing: 
Try to install layout-card trough HACS

What I expected to happen: 
Show all the newer Version numbers up to actually 16

What happened instead: 
It only shows the "old" version numbers including 2.3.1 as newest Version

**Minimal** steps to reproduce: 
Install HACS
Get new Repository layout-card 

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
![image](https://user-images.githubusercontent.com/19861673/151324961-a304ae6e-46c3-4ef5-945d-8cb63d4bf14b.png)

**Comment by thomasloven** [comment]
2.3.1 IS the latest release.
The release numbering changed 18 months ago. Where did you even *find* 16?

**Comment by scheilch** [comment]
Hi thomas, I found version 16 here in the tags. So the versioning now is like the scheme Major.Minor.Bugfix?

Then this issue can be closed.
