### ISSUE TITLE
Would love to be able to style the background of the layout cards

### ISSUE THREAD

**Issue by msymms** [thomasloven/lovelace-layout-card#182]
I am coding a workaround at the moment by adding key.startsWith("background") to the addStyles function and then styling it in the layout dictionary in the config file, but that is a sloppy way to do it.

**Comment by msymms** [comment]
Well, my solution works well in a browser, but not in the iOS apps.  I cannot make the cards within the grid transparent.  Back to the start now.

**Comment by thomasloven** [comment]
I recommend [card-mod](https://github.com/thomasloven/lovelace-card-mod) for this.
