### ISSUE TITLE
View types missing

### ISSUE THREAD

**Issue by egobuster1** [thomasloven/lovelace-layout-card#183]
My Home Assistant version: 2022.2.0

Layout-card version (FROM BROWSER CONSOLE): 2.3.1

What I am doing: it appears as if under the view layout all I get now is masonry, sidebar, and panel 1 card.
there's also no area to enter in the max-width code and columns. 

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by egobuster1** [comment]
I went into Configuration ==>> Dashboard ==>> resources
and found the JS file for lay out card and when i opened it I just clicked update and it came back

**Comment by egobuster1** [comment]
well it seems after upgrading to 2022.2.1 the issue is back and my fix last time doesn't seem to be working anymore.

**Comment by RudiKlein** [comment]
Same issue here. Still in 2022.2.5

**Comment by RudiKlein** [comment]
Hi,

Just updated the OS to 7.4 and checked if anything changed on the layout card, and it did. The missing views are no longer missing. Everything seems to be working fine. However, the dashboard I used to test it appeared to be empty, with all cards gone. I'm not sure if I caused it myself or the switch from Masonry to Masonry (layout-card) was the culprit. It was late in the evening....

**Comment by andbad** [comment]
Same problem here with HA Core 2022.2.9.

By(t)e

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#uncaught-syntaxerror-unexpected-token-

**Comment by andbad** [comment]
I tried to download from RAW already, and get js file from release zip, but error remains.
Is it possibile that HA caches it in some way? I also try to add "?v=2" but not works.

By(t)e

**Comment by thomasloven** [comment]
That should be fixed now.
