### ISSUE TITLE
No layout option to select

### ISSUE THREAD

**Issue by andbad** [thomasloven/lovelace-layout-card#185]
My Home Assistant version: 2022.2.9

Layout-card version (FROM BROWSER CONSOLE): 2.4.0

What I am doing: I copied the js file (downloaded from RAW link) to /www folder, then I configure module in "Settings/Resource"

What I expected to happen: When I click on pencil icon in Lovelace to configure layout of the page, I should find custom Masonry,
Horizontal, Vertical and Grid layout

What happened instead: I find only standard layout

**Minimal** steps to reproduce: 

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:
```
LAYOUT-CARD 2.4.0 IS INSTALLED 
layout-card.js?v=199:216 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'defaultValue')
    at F.t.updated (:58123/local/lovelace-custom/layout-card.js?v=199:216:3437)
    at F._$AE (:58123/frontend_latest/app.1bcfdc44.js:1248:30525)
    at F.performUpdate (:58123/frontend_latest/app.1bcfdc44.js:1248:30305)
    at F.scheduleUpdate (:58123/frontend_latest/app.1bcfdc44.js:1248:29887)
    at F._$EC (:58123/frontend_latest/app.1bcfdc44.js:1248:29795)
```

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Cortexian** [comment]
I am also experiencing this problem with 2022.2.9

**Comment by blandrd** [comment]
This is happening to me as well, with the same error as the first post:

`LAYOUT-CARD 2.3.1 IS INSTALLED 
2layout-card.js?hacstag=156434866231:194 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'defaultValue')
    at F.t.updated (layout-card.js?hacstag=156434866231:194:3001)
    at F._$AE (styles.ts:368:1)
    at F.performUpdate (styles.ts:368:1)
    at F.scheduleUpdate (styles.ts:368:1)
    at F._$EC (styles.ts:368:1)
t.updated @ layout-card.js?hacstag=156434866231:194
_$AE @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368`

**Comment by kicker10BOG** [comment]
I also no longer see the same layout options as before. I have it installed through HACS.

**Comment by variada** [comment]
> I also no longer see the same layout options as before. I have it installed through HACS.
> 
> My existing grid layout works, but I can't edit it through the gui or change to the grid on another panel.

can confirm exactly that. only non-HACS install. no dropdown options for the lovelace tabs. existing layouts work fine. can only edit it via the raw editor.

did they rename the dropdown and options text field maybe?

**Comment by jjrytko** [comment]
> I also no longer see the same layout options as before. I have it installed through HACS.
> 
> My existing grid layout works, but I can't edit it through the gui or change to the grid on another panel.

I can also see the same problem. Non-HACS install (Home Assistant 2022.2.9, Docker: true)

**Comment by sillvva** [comment]
I am experiencing this problem as well with HACS install on 2022.3.0. It is still working with YAML configuration, but the UI options are missing.

![image](https://user-images.githubusercontent.com/5138384/156660961-0d9b9b0a-90f9-46c9-9fad-5c3548b2d779.png)

**Comment by compujunk** [comment]
I am also experiencing this problem with HA 2022.3.0

**Comment by RenWal** [comment]
As a workaround, you can use the raw configuration editor from the menu in the top right corner. For each entry in `views`, you can set the `type` property, for example, `type: custom:grid-layout`. Then, also define the `layout` property and put all of the config options for your layout in there.

**Comment by cloudbr34k84** [comment]
yep im not getting anything. Hopefully this will be updated. This should be a standard in HA anyway

**Comment by OMVMMG** [comment]
Same here.
LAYOUT-CARD 2.4.1
Home Assistant 2022.3.1

View types not showing anymore.

**Comment by firstchair** [comment]
Same wise, I see this error:
`layout-card.js?hacstag=156434866241:47 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at St._setGridStyles (/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866241:47:3854)
    at St.setConfig `

**Comment by pickonedev** [comment]
Same here. 2.4.1, no layout tab/options

**Comment by mikastrup** [comment]
Same (with HACS)

**Comment by Jpsy** [comment]
Same here. 
My console error message is a bit different though:
```
layout-card.js?hacstag=156434866241:47 
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at St._setGridStyles (layout-card.js?hacstag=156434866241:47:3854)
    at St.setConfig (layout-card.js?hacstag=156434866241:47:3034)
```

**Comment by pickonedev** [comment]
I think that this repository has been forgotten 👎

**Comment by Jpsy** [comment]
Yepp, works beautifully again.
Thanks @thomasloven !

**Comment by firstchair** [comment]
Thanks @thomasloven :+1::+1:

**Comment by OMVMMG** [comment]
All good now. Thank you!

**Comment by yangtfu** [comment]
This happens again in  2022.4.3
