### ISSUE TITLE
Scrolling jumps to top on mobile device

### ISSUE THREAD

**Issue by gekim84** [thomasloven/lovelace-layout-card#19]
on a long scroll 1 column, it seems that the page jumps back up to top when scrolling for the 1st time on a refreshed page starting from the top.

**Comment by IDmedia** [comment]
For me this happens every time I scroll all the way to the top. When scrolling down it jumps to the top, then I'm able to scroll down further, but if I scroll all the way to the top again then it happens again.

**Comment by thomasloven** [comment]
Please try this with the latest version and let me know if there's still a problem.
