### ISSUE TITLE
Make break conditional

### ISSUE THREAD

**Issue by jblancoperez** [thomasloven/lovelace-layout-card#2]
This way of specifying layout is great for a wall mounted tablet.
I can make everything the way I want, but it breaks when using my phone.

Could be possible to switch to a more "auto"  or responsive layout when using a smaller screen ? Something like that should cover any possible configuration necessity.

**Comment by Whytey** [comment]
I thought this was hurting me too, but I found the undocumented 'max_columns:' config option.  Works a treat now :)

**Comment by thomasloven** [comment]
You could also try playing around with the `column_width` option. I've updated the readme to include my debugging features.
