### ISSUE TITLE
Missing dropdownlist to select the correct view

### ISSUE THREAD

**Issue by magtimmermans** [thomasloven/lovelace-layout-card#234]
My Home Assistant version: 2023.1.5

Layout-card version (FROM BROWSER CONSOLE): 2.4.2

What I am doing:
Try to create a new view.

What I expected to happen:
That I can select a layout from the new view card

What happened instead:
There is no dropdownlist:

![image](https://user-images.githubusercontent.com/17949840/213536157-d098bd01-cc07-47fc-80b3-6ec979419ec0.png)

console error messages:
`
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'options')
    at F._schema (lovelace-layout-card.js:215:2128)
    at F.value (hui-dialog-edit-view.ts:571:1)
    at F.update (styles.ts:372:1)
    at F.performUpdate (styles.ts:372:1)
    at F.scheduleUpdate (styles.ts:372:1)
    at F._$EC (styles.ts:372:1)
`

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by radhoo2k10** [comment]
Got the same problem. 

Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

![image](https://user-images.githubusercontent.com/78762281/217071799-550df309-d457-4553-8a7a-a0f61912c23c.png)

Installed via hack using the instruction from this: https://www.youtube.com/watch?v=9cm2CBBdr_I
