### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this._observer.disconnect')

### ISSUE THREAD

**Issue by RedNo7** [thomasloven/lovelace-layout-card#247]
**My Home Assistant version:**
2023.5.1

**Layout-card version (FROM BROWSER CONSOLE):**
2.4.4

**What I am doing:**
checking the logs

**What I expected to happen:**
nothing - everything seems OK in my dashboards

**What happened instead:**
n/a

**Minimal** steps to reproduce:
not sure.  I use this card everywhere.  Looking for pointers to trace this log entry.

**Error messages from the browser console:**
error from the logs (not sure what 'browser console is"
```
Logger: frontend.js.latest.202305032
Source: components/system_log/__init__.py:257 
First occurred: 10:25:36 (8 occurrences) 
Last logged: 10:33:33

:0:0 Script error.
http://192.168.1.100:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866242:13:3316 TypeError: undefined is not an object (evaluating 'this._observer.disconnect')

```
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by RedNo7** [comment]
huh.  I restarted HA and the issue has gone

**Comment by jalejandro0211** [comment]
> **My Home Assistant version:** 2023.5.1
> 
> **Layout-card version (FROM BROWSER CONSOLE):** 2.4.4
> 
> **What I am doing:** checking the logs
> 
> **What I expected to happen:** nothing - everything seems OK in my dashboards
> 
> **What happened instead:** n/a
> 
> **Minimal** steps to reproduce: not sure. I use this card everywhere. Looking for pointers to trace this log entry.
> 
> **Error messages from the browser console:** error from the logs (not sure what 'browser console is"
> 
> ```
> Logger: frontend.js.latest.202305032
> Source: components/system_log/__init__.py:257 
> First occurred: 10:25:36 (8 occurrences) 
> Last logged: 10:33:33
> 
> :0:0 Script error.
> http://192.168.1.100:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866242:13:3316 TypeError: undefined is not an object (evaluating 'this._observer.disconnect')
> ```
> 
> **By putting an X in the boxes ([X]) below, I indicate that I:**
> 
> * [x]  Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
> * [x]  Have made sure I am using the latest version of the plugin.
> * [x]  Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
> * [x]  Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

Hi I'm getting a message that looks similar...

`2023-05-05 08:32:20.521 ERROR (MainThread) [frontend.js.latest.202305032] http://homeassistant:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866244:13:3317 Uncaught TypeError: Cannot read properties of undefined (reading 'disconnect')
`

Not fixed with restart...

**Comment by RedNo7** [comment]
> Not fixed with restart...

I've re-opened it for you.
