### ISSUE TITLE
Keyboard disappearing

### ISSUE THREAD

**Issue by tenkaibr** [thomasloven/lovelace-layout-card#25]
First of all I would like to thank you for your work! This plugin is very useful. However, I'm having a very specific problem on my cell phone. When I try to include one entry in the Shopping List Card, the keyboard simply disappears.

In the example below I put one card out of the layout and another inside:

![giphy](https://user-images.githubusercontent.com/39348260/60793023-340f3680-a13d-11e9-9108-09fc48f0e202.gif)

**Comment by IDmedia** [comment]
I'm also struggling with this issue

**Comment by andjohansen** [comment]
I'm also having the exact problem. 
Other than that, this card is very good.

**Comment by Svarstad** [comment]
Having the same problem aswell 
`resources:
  - url: /local/custom-lovelace/lovelace-card-tools/card-tools.js?track=true
    type: js
  - url: /local/custom-lovelace/lovelace-layout-card/layout-card.js?track=true
    type: js

views:
  - !include lovelace/test.yaml
`

**Comment by Svarstad** [comment]
After what I could see, when selecting the input field it rebuilds the #columns again. Then the "deselecting" makes sense... But how to solve it?

**Comment by Svarstad** [comment]
So I read a little of the code and made the quickest and perhaps dirtiest workaround for the keyboard issue... Not sure if this is a problem for iPhones aswell, but the keyboard on android pushes the screen up and not laying over the content so its resizing.. 

```
    if (screen.width > 1055 ){
        window.addEventListener('resize', () => this.build());
    }
```
but it works ¯\_(ツ)_/¯

**Comment by thomasloven** [comment]
Hi.

Please try this with the latest version and let me know if there are still issues!

See #34

**Comment by tenkaibr** [comment]
> Hi.
> 
> Please try this with the latest version and let me know if there are still issues!
> 
> See #34


Still with the same problem. I updated all the pluggins and cleared the cache but nothing. Running HA 0.101.3

**Comment by thomasloven** [comment]
Please try version 2.0.0.
