### ISSUE TITLE
Nesting custom grid card with areas possible?

### ISSUE THREAD

**Issue by dmidthun** [thomasloven/lovelace-layout-card#254]
Has anyone been able to nest custom grid layout cards within a custom layout card?

case:
I have a layout:
"sidebar  sidebar  sidebar  testing  testing  testing  . testing2  testing2 testing2" 

within the testing area, I am trying to get a second layout:
"preset  remote  remote  remote"

I can get the first layer to sit where it's supposed to, but the underlying (nested) cards do not correspond to the 4 column layout. I am able to get a card in the first column, but cannot for the life of me figure out why i cannot get another card to go to the remaining (3) remote column and fit the width correctly

**Comment by dmidthun** [comment]
I figured it out

**Comment by nobodyspecial** [comment]
> I figured it out

how?
