### ISSUE TITLE
Add support to HACS 

### ISSUE THREAD

**Issue by jokerigno** [thomasloven/lovelace-layout-card#26]
Hi,

It would be great if you will add support for this card in the brand new home assistant community store.

Thank you in advance!

**Comment by Nihvel** [comment]
Hi, you can still use it.

1. Locate here on Github the link to the project, in this case:
`https://github.com/thomasloven/lovelace-layout-card`
2. Open HACS, find the "SETTINGS" link/text in the upper right corner.
3. Add this repository where is says "ADD CUSTOM REPOSITORY" - Select Plugin as type.

Note: layout-card requires card-tool. Add this project as well ;)

**Comment by thomasloven** [comment]
As mentioned *any* custom cards can be added to HACS manually.
I'll add this after a bit of restructuring. Eventually.

**Comment by jokerigno** [comment]
> Hi, you can still use it.
> 
> 1. Locate here on Github the link to the project, in this case:
>    `https://github.com/thomasloven/lovelace-layout-card`
> 2. Open HACS, find the "SETTINGS" link/text in the upper right corner.
> 3. Add this repository where is says "ADD CUSTOM REPOSITORY" - Select Plugin as type.
> 
> Note: layout-card requires card-tool. Add this project as well ;)

thank you! :)
