### ISSUE TITLE
Card causes the new `Sections` view type to be greyed out in the View Configuration menu

### ISSUE THREAD

**Issue by raman325** [thomasloven/lovelace-layout-card#274]
My Home Assistant version: 2024.3.0b0

Layout-card version (FROM BROWSER CONSOLE): 2.4.4

What I am doing: Trying to create a view using the new `Sections` view type

What I expected to happen: The view type is selectable

What happened instead: The view type is not selectable

**Minimal** steps to reproduce:

1. Update to 2024.3.0b*
2. Enable layout-card
3. Create a new view, and in the view configuration menu, open the View type drop down menu
4. Observe that `Sections` is greyed out

Additional details:
Screenshots and the potential root cause is logged here, see karwosts last comment for potential root cause: https://github.com/home-assistant/frontend/issues/19916

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jlpouffier** [comment]
Some additional context:
The new `sections` view type is, for now, experimental and not compatible with any other view type.

This means that the behavior implemented in Home Assistant is the following:

- If the view is empty (no card, no section) : Any view type can be picked
![CleanShot 2024-02-29 at 09 23 39](https://github.com/thomasloven/lovelace-layout-card/assets/5878296/e979a213-6498-4d84-ab09-d14d7a9ef1ec)

- If the view contains cards on a view type other than `sections`.(100% of the views today): `sections` cannot be picked
![CleanShot 2024-02-29 at 09 23 08](https://github.com/thomasloven/lovelace-layout-card/assets/5878296/61193bef-fa42-47b9-95e5-76fe178162ed)


- If the view contains cards in sections on a view type `sections`: nothing else can be picked
![CleanShot 2024-02-29 at 09 24 06](https://github.com/thomasloven/lovelace-layout-card/assets/5878296/26885877-345b-4ee7-949e-13aef10dd529)
