### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by RolandGoud** [thomasloven/lovelace-layout-card#30]
First of.... this solves a lot of the card control issues in lovelace for me: Kudos (and thank you)

Maybe this is not the place (or maybe this has been asked already, but I can't find it). I would love to have 1 big card spanning all columns like a hero image but I an't figure out if this is at all possible. 

And if it is not, do you see any ways to implement this in the layout-card?

Good stuff, again!!!

**Comment by thomasloven** [comment]
It can be done by nesting layout-cards.
See example picture at bottom of latest readme update.
