### ISSUE TITLE
Layout-card not working

### ISSUE THREAD

**Issue by DarvosBR** [thomasloven/lovelace-layout-card#4]
Ok so, something really akward just happend!

I was using the layout-card in my homeassistant without the card-tools, i'm using the HAss both in my pc and in my raspberry with touchscreen. no problem with that.

I recently faced a problem with my raspberry forcing me to reinstall the whole thing again.

Now something akward happend, the msg : Can't find card-tools appears only on my touchscreen but not in my pc browser! 

and yes i already install te card-tools.

well now i need help! how can we do this?

**Comment by Fusion** [comment]
This is a somewhat uninformed answer, but have you fully flushed your browser's cache? I've observed weird behaviors when upgrading my components if I skip that step.

**Comment by thomasloven** [comment]
Try updating your browser, or setting `javascript_version` to `latest`.
