### ISSUE TITLE
layout card "behind" a state-switch card

### ISSUE THREAD

**Issue by tomeeka** [thomasloven/lovelace-layout-card#47]
In the latest version (v8) if I put the layout-card "behind" a state-switch card, all cards all in one column for every state. Rolled back to v6 and the default state is rendered fine. If I switch to a different state those new cards are in one column. After refreshing the page they are rendered fine.

**Comment by thomasloven** [comment]
Could you please try version 10, and see if that fixes it?

**Comment by tomeeka** [comment]
The default state-switch card is okay now if I open the page. But when I switch on a hidden state-switch card which has a layout-card in it the content is in one column. Refreshing the page fixes it temporarily. Looks like only the visible layout-card is appearing correctly after I reload the page.

Example:
`
- title: Rendszer
  path: rendszer
  icon: mdi:information
  panel: true
  cards:

  - type: custom:layout-card
    layout: vertical
    max_width: 100%
    cards:

      - type: custom:layout-card
        layout: horizontal
        column_num: 4
        max_width: 125
        cards:

          - type: "custom:button-card"
            name: RASPBERRY
            icon: mdi:raspberry-pi
            size: 50px
            styles:
              card:
                - font-size: 12px
                - font-weight: bold
            tap_action:
              action: navigate
              navigation_path: "#raspberry"
          - type: "custom:button-card"
            name: ROUTER
            icon: mdi:router-wireless
            size: 50px
            styles:
              card:
                - font-size: 12px
                - font-weight: bold
            tap_action:
              action: navigate
              navigation_path: "#router"

      - type: custom:state-switch
        entity: hash
        default: raspberry
        states:

      #############################
      ##  RASPBERRY
      #############################

          raspberry:

            type: custom:layout-card
            layout: vertical
            cards:

            - type: entities
              title: Raspberry
              show_header_toggle: false
              entities:
                - entity: sensor.date_time
                  name: Rendszeridő
                - entity: sensor.last_boot
                  name: Uptime
                  format: total
                # - sensor.processor_use
                # - sensor.cpu_temperature
                # - sensor.memory_use_percent
                - sensor.swap_use_percent
                - entity: sensor.disk_use_percent
                  name: SSD

            - type: entities
              title: Home Assistant
              show_header_toggle: false
              entities:
                - entity: sensor.hass_started
                  name: Uptime
                  format: total
                - entity: binary_sensor.updater
                  name: Update

            - break
            
            - type: custom:mini-graph-card
              hour24: true
              entities:
                - sensor.processor_use
            - type: custom:mini-graph-card
              hour24: true
              entities:
                - sensor.cpu_temperature
            - type: custom:mini-graph-card
              hour24: true
              entities:
                - sensor.memory_use_percent
                

      #############################
      ##  ROUTER
      #############################

          router:

            type: custom:layout-card
            layout: vertical
            cards:

              - type: entities
                title: Router
                show_header_toggle: false
                entities:
                  - sensor.connectivity_router
                  - entity: sensor.router_started
                    name: Uptime
                    format: total
                  # - sensor.router_cpu
                  # - sensor.router_mem
                  # - sensor.speedtest_download
                  # - sensor.speedtest_upload
                  # - sensor.speedtest_ping
              
              - break

              - type: entities
                title: Gatewayek
                show_header_toggle: false
                entities:
                  - sensor.connectivity_zigbee2mqtt
                  # - sensor.zigbee2mqtt_bridge_state
                  # - sensor.connectivity_zigbee_router
                  - sensor.connectivity_xiaomi_gateway
                  - sensor.connectivity_wemos_milight
                  - sensor.connectivity_wemos_ac
`

**Comment by thomasloven** [comment]
Please try release 12.

**Comment by tomeeka** [comment]
Fixed, thank you!
