### ISSUE TITLE
alignment problem

### ISSUE THREAD

**Issue by madmicio** [thomasloven/lovelace-layout-card#49]
congratulations for the excellent work.
I have a problem in the grid mode.
I used the same entity and the same type of card.
as seen in the photo, the cards of the first column are not aligned with the cards of the second column.
how can i solve?
![errore](https://user-images.githubusercontent.com/42836292/72690667-ec6f5b80-3b1e-11ea-9454-09b921d8d788.jpg)

**Comment by thomasloven** [comment]
Please try release 12.

**Comment by madmicio** [comment]
perfect!
