### ISSUE TITLE
Latest release (v10) not working/breaks Lovelace views in Fully Kiosk Browser

### ISSUE THREAD

**Issue by sbowater** [thomasloven/lovelace-layout-card#52]
I use Fully Kiosk Browser on Fire HD 8 tablets for wall mounted kiosks in place of my old alarm panels.  After updating this extension to latest version earlier today, Fully Kiosk exhibited very odd behavior -- failing to load Lovelace at all or loading just a portion of the header and no other content.  Reverted to v9 and, cleared cache and rebooted tablets and all now back to normal.

**Comment by freebsdgirl** [comment]
Latest update also causes firefox to stop working. CPU fans start spinning, page stops responding when it tries to load. Going directly to the url of a page that doesn't use layout card works fine. Downgraded to the previous version, and the problem went away. Wish I could get more info, but the developer console also locks up.

**Comment by mariantr** [comment]
same problem on desktop chrome and ios companions app 2.0

**Comment by sbowater** [comment]
I have isolated my particular issue to the use of v10 layout-card's 'column_width' in conjunction with 'panel: true' for the view.  This combination works fine for me in Chrome on the same hardware but causes Fully Kiosk (1.36.1-fire) to hang when loading/rendering the page (appears to get stuck in a loop).  Having 'panel: false' renders as expected.  For now I have rolled back to v9 and it also renders as expected.  See sample 'ui-lovelace.yaml' below and let me know what other info I can provide to help problem solve.

<pre>
resources:
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js 
title: Home
views:
  - title: Home
    path: home
    panel: true
    badges: []
    cards:
      - type: 'custom:layout-card'
        column_width:
          - 30%
          - 60%
        cards:
          - type: vertical-stack
            cards:
              - type: entity-button
                entity: person.steve
              - type: entity-button
                entity: person.steve
              - type: entity-button
                entity: person.steve
          - type: vertical-stack
            cards:
              - type: entity-button
                entity: person.steve
              - type: entity-button
                entity: person.steve
</pre>

**Comment by AngellusMortis** [comment]
I am also getting the same issue on v10/v11 on both Android/Home Assistant and Windows 10/Edge Chromium based browser.

**Comment by sbowater** [comment]
Updating this issue:  I upgraded the other day to v11 and my layout started to work again.  A few minutes ago I updated to v12 (changelog says rendering improvements) and it broke again for me with the same symptoms as the original post.

**Comment by Windmelodie** [comment]
I have the same issue with chrome and could limit the root cause to "column_width" set with percentage values.
After replace 
`column_width: [10%, 60%, 10%, 10%, 10%]`
with 
`flex_grow: [10, 60, 10, 10, 10]`, 
the issue is fixed. 
flex_grow effects the sames as percentage column width in my configuration

**Comment by thomasloven** [comment]
Please try version 2.0.0.
