### ISSUE TITLE
Latest release (v12) not working correctly on Safari and iOS app

### ISSUE THREAD

**Issue by Phontana** [thomasloven/lovelace-layout-card#57]
I installed the latest version of the layout-card yesterday and it works like before in Chromium based browsers, but it does not work correctly in Safari on macOS and in the iOS app. It only shows 1 column despite the screen being large enough for more columns, like the view is not set to panel mode (which it is).

I see this error in the logs: 

`http://10.0.1.10:8123/lovelace/dashboard:0:0 ResizeObserver loop limit exceeded.`

**Comment by thomasloven** [comment]
Release 13 should take care of that.

**Comment by Phontana** [comment]
I just installed v13 and it seems to work again, thanks!
