### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by smhgit** [thomasloven/lovelace-layout-card#60]
Document says use module but for me, in 0.107.0 js is working:

> Install layout-card.js as a module.

That is what working for me:

```
- url: /hacsfiles/lovelace-layout-card/layout-card.js
  type: js
```

**Comment by shauder** [comment]
I am using module on 0.107.5

```
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
```

**Comment by Lekesoldat** [comment]
I've tried both with type js and module on 0.107.3 without results. Updating to 0.107.6 now and will respond with results.

**Comment by magicbret** [comment]
Hi,
Exactly same issue for me. Module is not working. Usage of horizontal or vertical has no effect.

Here is my module to see if a particular one can interfer

- url: https://use.fontawesome.com/releases/v5.2.0/css/all.css
  type: css
- url: /hacsfiles/custom-header/custom-header.js
  type: module
- url: /hacsfiles/lovelace-hass-aarlo/hass-aarlo.js
  type: module
- url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  type: module
- url: /hacsfiles/meteo-france-weather-card/meteo-france-weather-card.js
  type: module
- url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
  type: module
- url: /community_plugin/weather-card/weather-card.js
  type: module
- url: /hacsfiles/garbage-collection-card/garbage-collection-card.js
  type: module
- url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js  
  type: module
- url: /hacsfiles/bar-card/bar-card.js  
  type: module
- url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  type: module
- url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  type: module
- url: /hacsfiles/battery-state-card/battery-state-card.js
  type: module    
- url: /hacsfiles/lovelace-battery-entity/battery-entity.js
  type: module      
- url: /hacsfiles/ha-card-waze-travel-time/ha-card-waze-travel-time.js
  type: module

**Comment by thomasloven** [comment]
There's two ways to debug compatibility problems.
Either I find, download and install all of the plugins on your list, guess how you have configured them and see what happens.
Or, you add a `#` to the beginning of some of those lines, and see if that fixes the problem.

@smhgit Something other than what's stated in the readme **also** working isn't really a problem... is it?
