### ISSUE TITLE
aligning elements in grid layout

### ISSUE THREAD

**Issue by angelnu** [thomasloven/lovelace-layout-card#61]
Thanks for your card - I use it to create a table with multiple button cards for setting up my thermostat temperatures from a single page.

I noticed that I need to set up the `align-items: center;` to avoid that the elements get aligned to the top of the cells. I did that with the developer tools in the browser since I was not able to find a way to do it directly in the yaml. It looks like this:

```
display: grid;
grid-template-rows: 0% auto auto auto auto auto auto auto auto auto auto auto;
grid-template-columns: 10% 0.5fr 1fr 2fr 1fr 1fr 2fr 1fr 0.5fr 1fr 2fr 1fr 1fr 2fr 1fr 0.5fr 1fr 2fr 1fr 1fr 2fr 1fr 0.5fr 1fr 2fr 1fr 1fr 2fr 1fr;
align-items: center;
```

Could you add an option to set up the align-items for grid layouts? I can also contribute a PR if needed.

And here a screenshot of how it looks before and after - I intentionally made the screen small to allow seeing the effect from align-items more clearly.

## Before
<img width="852" alt="image" src="https://user-images.githubusercontent.com/4406403/77257175-fb839e80-6c72-11ea-8a68-c53f8d01cdec.png">

## After
<img width="855" alt="image" src="https://user-images.githubusercontent.com/4406403/77257164-eeff4600-6c72-11ea-9757-16b93b26594d.png">

**Comment by eggman0131** [comment]
I agree, align-items support would be great

**Comment by thomasloven** [comment]
Added `gridplace:` in release 14!
