### ISSUE TITLE
Version 14 seems to break display on mobile devices 

### ISSUE THREAD

**Issue by adonno** [thomasloven/lovelace-layout-card#80]
After updating I had an issue with my cards not being shown one under another on mobile devices 
I had to revert back to 1.3 in order to have it working properly 

you can find the config here https://paste.ubuntu.com/p/Z5nG2GKdvZ/

**Comment by adonno** [comment]
Version 13:

![image](https://user-images.githubusercontent.com/13216947/85933074-0c2b5c80-b8d3-11ea-9f41-310c96897354.png)

![image](https://user-images.githubusercontent.com/13216947/85933080-177e8800-b8d3-11ea-9c62-c1ccaa6bf686.png)

Version 14 & 15

![image](https://user-images.githubusercontent.com/13216947/85933084-25340d80-b8d3-11ea-90f8-8385736d1c1b.png)

![image](https://user-images.githubusercontent.com/13216947/85933087-2f560c00-b8d3-11ea-8841-0f902449f5fc.png)

**Comment by rccoleman** [comment]
I had the same issue with "horizontal" and had to change to "auto" to make it format it properly.  Thomas said on Discord that he thought it should still work, but it doesn't for either of us.

**Comment by ronaldheft** [comment]
I'm seeing the same thing. Browser widths that would normally display 1 column are displaying 2 columns. On my computer, if I resize the window a few times, sometimes it will snap back to 1 column, but on my phone it's seems to be stuck on 2 columns.

I'm using the `vertical` layout type.

**Comment by adonno** [comment]
thank for the tip, I tried "auto" and it showed 3 instead of 4 columns, so I added: "min_columns: 4" and it still showed only 3 columns

**Comment by Phontana** [comment]
When I view on my phone from the Home Assistant iOS app, I have the correct behavior when connected on internal network, but when connected from outside I have the behavior described above (2 instead of 1 column). When I switch back to internal network, it shows 1 column again.

**Comment by pinkywafer** [comment]
same issue here.  I've also tried setting `min_width: 300` but that ressuled in the half of the left column missing off the left side of the screen, and the right column off the right (but reachable by swiping!)
I'm using vertical mode, and using auto gives undesired layout

**Comment by dvd77** [comment]
> When I view on my phone from the Home Assistant iOS app, I have the correct behavior when connected on internal network, but when connected from outside I have the behavior described above (2 instead of 1 column). When I switch back to internal network, it shows 1 column again.

Sam here, also via Safari and iOS app when connected to internal netwerk it shows 2 columns, when connected via external it shows everything correctly

**Comment by jcomas** [comment]
I'm using vertical layout with same problem. Temporary workaround for me is set column width:

cards:
...
column_width: 500
layout: vertical
type: 'custom:layout-card'

**Comment by thomasloven** [comment]
Please try release 16.

**Comment by adonno** [comment]
fixed for me

**Comment by pinkywafer** [comment]
Fixed for me too.

Thanks
