### ISSUE TITLE
Break points now not ignored on the phone, 2 small column (out of 4) showed instead of a single one

### ISSUE THREAD

**Issue by SeLLeRoNe** [thomasloven/lovelace-layout-card#81]
Hi there,
I have updated today this card to latest release and on my phone now I do have 2 (50%) columns instead of one (100%)

Is there any new option that might cause this?
My config it's actually fairly simple:

```
  - type: custom:layout-card
    layout: vertical
    cards:
```
With some "- break" when I want a new column (I presume those were actually ignored on the phone before so it should show a single long column) while now they seems to be applied.
The oddest part is that just 2 columns are showed while technically the view has 4.

Any suggestion? 
Do you need a screenshot?

Thanks :)
Andrea

**Comment by thomasloven** [comment]
Please try release 16.

**Comment by SeLLeRoNe** [comment]
Hi Thomas,
Yes that fixed it!

Thank you very much :)
Andrea
