### ISSUE TITLE
Climate control losing text

### ISSUE THREAD

**Issue by stowers95120** [thomasloven/lovelace-layout-card#84]
When I add a climate (thermostat) control to a layout, it loses text. See the before and after screen shots - see how the text in the middle of the *before* shot ("68 - 82 Idle") is missing from the second shot.
<img width="274" alt="Screen Shot 2020-06-30 at 7 39 03 AM" src="https://user-images.githubusercontent.com/60076349/86144530-a5f93200-baaa-11ea-98ea-2591b61eb26e.png">
<img width="274" alt="Screen Shot 2020-06-30 at 8 16 00 AM" src="https://user-images.githubusercontent.com/60076349/86144546-ac87a980-baaa-11ea-970d-3924e969a786.png">

**Comment by michaelarnauts** [comment]
I also recently started noticing this. I don't know what happened since this didn't happen before.

**Comment by thomasloven** [comment]
Please try version 2.0.0.
