### ISSUE TITLE
New version does not draw gauge cards

### ISSUE THREAD

**Issue by matejdro** [thomasloven/lovelace-layout-card#85]
As of https://github.com/thomasloven/lovelace-layout-card/commit/d785de69915a4d1915222c984334cae50576607c, all gauge cards that are direct descendant of layout card do not display.

When I open "Configure UI" screen, gauge does appear and remains displayed even after exiting configure menu. But after refreshing the page, it will disappear again.

This issue is not present in https://github.com/thomasloven/lovelace-layout-card/commit/af99dbaf90887e6ce1c4eba6535c495a440c47bb. One thing to note though is that even with the older version, gauge card appears to load asynchronously (it is not there after page is loaded, but it appears after about 250ms), so it might be something related with that.

**Comment by thomasloven** [comment]
Please try version 2.0.0.

**Comment by matejdro** [comment]
It works with the 2.2.2. Thanks!
