### ISSUE TITLE
Custom element doesnt exist

### ISSUE THREAD

**Issue by davidrustingha** [thomasloven/lovelace-layout-card#87]
Whenever I open the Home Assistant App on my iPhone, android tablet, or when I open home Assistant on my laptop I get the error
‘Custom elements doesn’t exist ..’
I have a couple of conditional cards and picture cards set up with a custom layout card for spacing.
This is what it looks like
![88026376-12a99e80-cb36-11ea-8ee1-c42b990b4221](https://user-images.githubusercontent.com/62120423/88046661-ac7e4500-cb50-11ea-932a-9091d2c1bec9.png)

This is how it should look
![88026628-7207ae80-cb36-11ea-8216-0e450e9dc138](https://user-images.githubusercontent.com/62120423/88046667-af793580-cb50-11ea-833e-1d9868e23c64.jpeg)

yaml config:
`type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:layout-card
        layout: grid
        gridcols: 100px
        gridrows: 100px
        cards:
          - type: picture
            image: /local/person_pictures/david.jpg
            gridrow: 1/2
            gridcol: 1/2
          - type: conditional #Thuis
            gridrow: 1/2
            gridcol: 2/4
            conditions: 
              - entity: device_tracker.life360_david_rusting
                state: 'home'
            card:
              type: markdown
              gridrow: 1/2
              gridcol: 2/4
              style: |
                ha-card {
                  height: 90px;
                }
              content: >
                {% if is_state_attr('device_tracker.life360_david_rusting', 'battery_charging', true) %}
                  **David is thuis.**
                  **Batterij heeft {{ state_attr('device_tracker.life360_david_rusting', 'battery')}}% en laad op.**
                {% else %}
                  **David is thuis.**
                  **Batterij heeft nog {{ state_attr('device_tracker.life360_david_rusting', 'battery')}}%.**
                {% endif %}`

The only way to fix it is to refresh the page several times until it loads correctly

**Comment by paddenstoeltje** [comment]
I have the same problem with the HA ipad app; "Custom element doesn't exist: layout-card". After reloading x times it works again. I have no problems in the browser nor in Android.

Wouter

**Comment by jonostanck** [comment]
Having the same problem...
![Screenshot_20200727-181655](https://user-images.githubusercontent.com/33318513/88565834-6e43c280-d035-11ea-8d3b-57b310c2b1f4.jpg)

**Comment by davidrustingha** [comment]
It sucks, but im glad im not the only one!

**Comment by jonostanck** [comment]
I've tried to find a reason why this happens and after disabling browser_mod it seems the issue is resolved. Maybe it will help you too.

**Comment by paddenstoeltje** [comment]
After updating browser_mod to 1.1.4 the problem seems to be gone.

**Comment by davidrustingha** [comment]
I still have the error sometimes. But I can work around it

**Comment by antoineguilbert** [comment]
Same error for me. When I disable panel mod its works (but all cards are in one colum now). If anybody have an idea :)

**Comment by thomasloven** [comment]
Please try version 2.0.0.

**Comment by glenn20** [comment]
I am seeing this errror: "Custom element doesn't exist: vertical-layout" on ther android app (phone and livingroom tablet). All is rendering fine in a chrome web browser. I have tried v2.1.0 and v2.0.0. Refreshing the page >10 times doesn't seem to help. I do not have browser-mod installed. 

Till yesterday I was just using the layout-card with the old "- break" syntax, but that stopped working on the web browser yesterday after upgrade to HACS 2 (Config is not an object: break) - although it kept working on the app. I updated my dashboard to using the newer custom:vertical-layout option and "type: custom:layout-break" and all is working just fine in the chrome web browser, but broken in the android app.

**Comment by thomasloven** [comment]
If something you removed is still working in only one browser, it's with 110% certainty a caching issue.
There's a setting for clearing the cache somewhere in the app, I believe - which is different from reloading resources.

**Comment by glenn20** [comment]
Thanks - wow - it is hard to get the app to flush its cache - I had to flush it in the android settings and restart the app.

**Comment by Ylinku** [comment]
flushing the cache in IPAD app works great. got similar error  "Custom element doesn't exist: layout-break" after upgrade to v2.0
Thanks.
