### ISSUE TITLE
add support for grid-template-areas | grid-area

### ISSUE THREAD

**Issue by kdw2060** [thomasloven/lovelace-layout-card#88]
Hello,

would you consider adding the `grid-template-areas` (on the layout card) and `grid-area` (on the contained cards) css properties for the grid layout?
I feel this would add more flexibility to the grid layout option.
Custom button card can maybe serve as an [example implementation](https://github.com/custom-cards/button-card#custom-fields) (the second custom fields example gives a good idea of the flexibility you get).

thx for considering,
regards,
Kris

**Comment by kdw2060** [comment]
Had a look at the card code in the mean time and it's not hard to implement, already have a working fork on my pc.
I'll try to add something to help with responsiveness as well, then make a pull request either with or without that extra.

btw, to correct my previous statement, I guess it's less a matter of flexibility and more of readability / ease of use. I personally find a grid layout defined with areas easier to visualise and understand.

**Comment by kdw2060** [comment]
#90 pull request opened

**Comment by thomasloven** [comment]
All CSS grid features are now available in version 2.0.0.
