### ISSUE TITLE
The card is not recognized by IOS 10.3.4

### ISSUE THREAD

**Issue by mfabiani53** [thomasloven/lovelace-layout-card#89]
Trying to run HA companion IOS app i get problems with the layout custom card together with other custom cards (for example stack-in-card and autoentities card).
I always get the issue "custom element doesn't exists: layout-card".
I checked if the IOS firmware installed on my IPad (10.3.4) is still supported by the app and i get the confirmation it's supported.
That's the only issue i am getting running the IOS companion app.

**Comment by thomasloven** [comment]
Please try version 2.0.0.
