### ISSUE TITLE
No longer works inside vertical-stack-in-card

### ISSUE THREAD

**Issue by wbilger** [thomasloven/lovelace-layout-card#9]
With the last update (Latest commit 2b29c00) no longer works in a vertical-stack-in-card. Cards still load, but if I used horizontal, they will just load vertical.
I didn't see anything in the documentation, just wondering if there is something to change?

**Comment by thomasloven** [comment]
Try the latest version. I made some structural changes that may have fixed things.

**Comment by thomasloven** [comment]
A week later I'll assume the latest version fixed the problem.
