### ISSUE TITLE
No longer in HACS?

### ISSUE THREAD

**Issue by AlperinJA** [thomasloven/lovelace-layout-card#91]
HACS 1.4.1 on Hassio 114.3.
Search for "layout" finds neither an integrations nor a frontend.

**Comment by thomasloven** [comment]
![image](https://user-images.githubusercontent.com/1299821/111053879-ebf2fc00-8467-11eb-85f7-d53bd4051d7a.png)

**Comment by axisremyj** [comment]
Same today, can't find "layout" or "layout-card" in HACS

**Comment by javo222** [comment]
Same today, can't find "layout" or "layout-card" in HACS
