### ISSUE TITLE
Unnecessary margin on #staging.grid

### ISSUE THREAD

**Issue by Giel88** [thomasloven/lovelace-layout-card#93]
layout-card.js contains the following:

```
      #staging.grid {
        margin: 0 -4px;
      }
```

This is causing a horizontal scroll on mobile. Is there any reason for this negative margin on the sides?

**Comment by FredericMa** [comment]
I'm having the same issue since I'm on 0.116.1.
In my case it even occurs desktop. Resized the window as a test but issue remains.
Setting the margin to `0 4px;` brings it back to normal. Completely removing it result in smaller margin on the edge compared to margin between cards.

**Comment by thomasloven** [comment]
This should be fixed with 2.0.0.
Please confirm.

**Comment by FredericMa** [comment]
Missed your previous comment. It is indeed fixed with 2.0.0. Thanks!

**Comment by thomasloven** [comment]
Thansk!
