### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by michaeltryl** [thomasloven/lovelace-layout-card#94]
i have this code

https://pastebin.com/RGxKG889

but it shows the gauge, but "input_boolean.pollen_saeson" is off so it should not show.
what can be wrong. it works if it is not in lovelace-layout-card

**Comment by gbdavidx** [comment]
its broken i think he gave up on his code i get 
Config is not an object
break

**Comment by michaeltryl** [comment]
Ok thanks i may look for something else then :)

**Comment by thomasloven** [comment]
Please, before assuming layout-card is at fault, try getting exactly the same thing to work **without** layout-card.
